# Generated by Django 4.1.2 on 2022-11-13 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_booking_options_booking_is_confirmed'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='service_type',
            field=models.CharField(choices=[('modelling', 'Modelling'), ('wedding', 'Wedding'), ('reception', 'Reception'), ('engagement', 'Engagement'), ('family_shoot', 'Family Shoot'), ('maternity', 'Maternity Shoot'), ('family_events', 'Family Events'), ('videography', 'Videography'), ('people_and_place', 'People and Place'), ('other', 'Other')], max_length=250, null=True),
        ),
    ]
