# Generated by Django 4.1.2 on 2022-12-01 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_alter_booking_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'ordering': ['is_cancelled', 'is_confirmed', '-created']},
        ),
        migrations.AlterField(
            model_name='contactmail',
            name='phone_number',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
