# Generated by Django 4.1.2 on 2022-11-03 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0006_alter_portfolio_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='photo_type',
            field=models.CharField(choices=[('tall', 'Tall'), ('wide', 'Wide'), ('big', 'Big'), ('Normal', 'Normal')], max_length=200, null=True),
        ),
    ]
