# Generated by Django 4.1.2 on 2022-11-06 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0008_photoportfolio_photo_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photoportfolio',
            name='photo_type',
        ),
        migrations.AddField(
            model_name='portfolio',
            name='photo_type',
            field=models.CharField(choices=[('wide', 'Wide'), ('big', 'Big'), ('Normal', 'Normal')], max_length=200, null=True),
        ),
    ]
