# Generated by Django 4.1.2 on 2022-11-07 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0009_remove_photoportfolio_photo_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='photoportfolio',
            name='photo_type',
            field=models.CharField(choices=[('wide', 'Wide'), ('big', 'Big'), ('Normal', 'Normal')], max_length=200, null=True),
        ),
    ]
