# Generated by Django 4.1.2 on 2022-11-07 08:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0010_photoportfolio_photo_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photoportfolio',
            name='portfolio',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='portfoliophoto', to='gallery.portfolio', verbose_name='Portfolio'),
        ),
    ]
