# Generated by Django 4.1.2 on 2022-11-07 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0012_alter_photoportfolio_portfolio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='photo_type',
            field=models.CharField(choices=[('tall', 'Tall'), ('wide', 'Wide'), ('big', 'Big'), ('normal', 'Normal')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='photoportfolio',
            name='photo_type',
            field=models.CharField(choices=[('wide', 'Wide'), ('big', 'Big'), ('normal', 'Normal')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='photo_type',
            field=models.CharField(choices=[('wide', 'Wide'), ('big', 'Big'), ('normal', 'Normal')], max_length=200, null=True),
        ),
    ]
