# Generated by Django 4.1.2 on 2022-11-08 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0013_alter_photo_photo_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolio',
            name='photo_type',
        ),
    ]
