# Generated by Django 4.1.2 on 2022-11-03 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Packages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('photo', models.ImageField(upload_to='images/packages/', verbose_name='Cover Photo')),
                ('description', models.TextField()),
                ('available', models.BooleanField()),
                ('price', models.IntegerField()),
            ],
        ),
    ]
