# Generated by Django 4.1.2 on 2022-11-03 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='packages',
            options={'ordering': ['available', '-created']},
        ),
        migrations.AddField(
            model_name='packages',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
