# Generated by Django 4.1.2 on 2022-11-04 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0002_alter_packages_options_packages_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packages',
            name='available',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=200),
        ),
    ]
