# Generated by Django 4.1.2 on 2022-11-08 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0004_alter_packages_available'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='packages',
            name='description',
        ),
    ]
